### ISSUE TITLE
Access for New Maintainers 2018

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/project#1]
As far as I heard, @just-me- and @Tom852 are the new maintainers of this project 🕺🎉 

I think it makes sense to [document all steps that are required to install new maintainers](https://github.com/studentenportal/project/blob/master/new_maintainer.md), so that this gets easier in the future!

Following steps need to be taken to make you full admins:

- [x] GitHub Organisation
  - [ ] Teams: We could make a new group @studentenportal/maintainer which always represents the active maintainer(s) so that they can be easily mentioned in issues?
- [ ] Pass Repository (Private)
  - For the pass repository, where all logins are stored as encrypted files, your GPG public keys must be added.  
Could you send them to our mailbox team@studentenportal.ch?  
If you need assistance with this, let me know 🙂 
- [ ] Email account for support (this requires prior access to pass)
  - User: `team@studentenportal.ch`
  - Password: See pass
  - IMAP: `imap.mail.hostpoint.ch` SSL
  - SMTP: `asmtp.mail.hostpoint.ch` SSL
- [ ] studentenportal.ch backend administrator access
  - https://studentenportal.ch/admin/front/user/, choose the users and set the Admin and Staff (in German: "Redakteur") flags.

**Comment by dbrgn** [comment]
> TODO: How to add django admins?

At https://studentenportal.ch/admin/front/user/, choose the users and set the Admin and Staff (in German: "Redakteur") flags.

**Comment by The-Compiler** [comment]
Can we close this? Looks like there is some documentation: https://github.com/studentenportal/project/blob/master/new_maintainer.md

**Comment by fabianhauser** [comment]
Yes, sadly, the transfer to the new maintainers did not succeed.
