### ISSUE TITLE
Add more Infos on Sponsoring

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/project#3]
- [ ] Studentenportal Server

**Comment by The-Compiler** [comment]
What does this mean exactly?

**Comment by fabianhauser** [comment]
The situation has changed slightly since I opened this issue, currently (and this should be documented):

- open\HSR "ownes" and finances studentenportal
- open\HSR sponsoring contracts apply to studentenporal also

- [ ] We can remove the "powered by nine" reference, as we integrated the server sponsoring in the regular Nine-Sponsoring of open\HSR
