### ISSUE TITLE
Google Analytics & Search Console Zugangsdaten

### ISSUE THREAD

**Issue by raphiz** [studentenportal/project#4]
Neulich hat mir Google mitgeteilt, dass sie der Meinung sind, ich sei der Inhaber von `studentenportal.ch`. Mit dazu gabs den Zugriff auf die Search-Console. Das kam ja nicht ganz überraschend, da mir Danilo vor ca. 1.5 Jahren Zugriff auf die Google Analytics Seite gegeben hat.
Ich schlage vor, dass ein separates Google Konto eingerichtet wird (mit Zugriffsdaten im Pass), welches der "offizielle Besitzer" der Domain und den damit verbundenen Tools (Analytics, Search Console etc) ist.
Am besten ein Maintainer richten ein Konto ein, speichern die Zugangsdaten im Pass und senden mir die E-Mail. Ich gebe dann die Rechte gerne ab :wink:

**Comment by fabianhauser** [comment]
Könntest du den neuen Account team@studentenportal.ch hinzufügen?
Merci! 😊

**Comment by raphiz** [comment]
:ballot_box_with_check: Habe ich soeben gemacht - könnt mich (und evlt. andere "Leichen" :wink: ) dann löschen :+1:

**Comment by fabianhauser** [comment]
Danke @raphiz, hab jetzt noch alle "Leichen" beseitigt :wink:
