### ISSUE TITLE
Zukunft Studentenportal

### ISSUE THREAD

**Issue by fabianhauser** [studentenportal/project#5]
Der Zustand vom (alten, physischen) Studentenportal-Server hat sich in der Zwischenzeit weiter verschlechtert:

```
a0       MegaRAID SAS PCI Express(TM) ROMB bios:MT33 fw:1.12.310-1112 encl:1 ldrv:1  rbld:80% batt:FAULT, module missing, pack missing, charge failed/0mV/0C
a0e252s2  SEAGATE ST3146855SS         136GiB  a0d0  online   errs: media:5  other:0
     write errors: corr:  0    delay:  0    rewrit:  0    tot/corr:  0    tot/uncorr:  0   
      read errors: corr: 57Mi  delay:562    reread:  0    tot/corr: 57Mi  tot/uncorr:  9   
    verify errors: corr:120Mi  delay:  2    revrfy:  0    tot/corr:120Mi  tot/uncorr:  5   
a0e252s5  SEAGATE ST3146855SS         136GiB  a0d0  online   errs: media:18 other:1 **predictive-failure**
     write errors: corr:  0    delay:  0    rewrit:  0    tot/corr:  0    tot/uncorr:  0   
      read errors: corr:107Mi  delay:  4Ki  reread:  0    tot/corr:107Mi  tot/uncorr: 28   
    verify errors: corr:205Mi  delay:  3    revrfy:  0    tot/corr:205Mi  tot/uncorr: 18   
```

> ***predictive-failure***

Es wäre daher dringend nötig, was anzureissen, ansonsten läuft das Studentenportal vermutlich nicht mehr lange (Konkret: Update Django, Migration Server). Aus meiner Sicht braucht es dafür einen neuen Maintainer, welche das ganze Projekt vorantreibt. Mein Vorschlag wäre, ein Rundmail an alle Informatik-Studierende zu senden.

@renklus: Könntest du das übernehmen?

**Stichwörter:**
- Studentenportal - von Studierenden für Studierende
- Bekannt für Zusammenfassungen, Prüfungen, Lösungen und Dozentenzitate
- Suchen dringend neue Maintainer, damit das Studentenportal weiter bestehen kann
- Stichwörter: Python, Django, Ansible
  - Eines davon reicht, um mitzuhelfen 😉

**Comment by dbrgn** [comment]
Noch ein kleines Status-Update: Der grosse Maintenance-Blocker, nämlich die Migration auf Django 1.8, ist nun endlich fertig! https://github.com/studentenportal/web/pull/193 Tricky war dabei der Wechsel vom 3rd-party DB-Migrationssystem "South" auf die DB-Migrationen von Django selbst.

Damit hat man nun ein halbwegs aktuelles Django, mit dem man weiterarbeiten kann. Die Migration auf 1.11 kann man auch bald noch machen (sollte kein grosser Aufwand sein), dann wären wir auf der aktuellen LTS.

Falls sich neue Maintainer finden, wäre ich bereit eine Übergabe zu machen und dabei die Codebase kurz vorzustellen. Am Wichtigsten wären momentan aber natürlich die Server.

---

Noch zum Zustand des Servers: GIB-Solutions hat damals mal gesagt, dass sie noch einen Spare-Server hätten. Falls man weiter bei ihnen bleiben möchte, könnte man sie wohl deswegen kontaktieren. Das bedingt aber einen physikalischen Besuch bei ihnen im Datencenter in Uitikon-Waldegg.

@fabianhauser hast du mal ein Backup gezogen?

**Comment by dbrgn** [comment]
Btw, wenn @renklus nicht reagiert können wir uns ev. auch direkt an den VSHSR wenden. Die dürfen auch Versände machen an alle Studis.

Ein Banner auf studentenportal.ch ("Looking for maintainers") wäre auch was! Könnte man in die Live-Version (direkt ins Template) reinhacken.

**Comment by The-Compiler** [comment]
Falls es Platz braucht für ein Backup, kann ich den (vorübergehend, für ein paar Monate oder so) gerne zur Verfügung stellen auf meiner persönlichen Infrastruktur.

**Comment by fabianhauser** [comment]
Danke @dbrgn für deinen Einsatz! 🎉 

Betreffend Backup: Ich habe mir soeben wieder eins auf den Laptop gezogen. Mittelfristig sollte das auf den FTP-space vom VSHSR gehen (siehe studentenportal/deploy-new#12), danke trotzdem für das Angebot @The-Compiler 😊.

Aktuell sind ja "Semesterferien". Ich würde daher vorschlagen, mit dem Rundmail noch zu warten bis im neuen Semester.  
Das Banner ist ebenfalls eine gute Idee, allerdings wird das vermutlich erst bei der nächsten Prüfungsphase wirklich wahrgenommen, würde daher erst mal das Rundmail versuchen 🙂

----

Ah noch betreffend:
> Noch zum Zustand des Servers: GIB-Solutions hat damals mal gesagt, dass sie noch einen Spare-Server hätten. Falls man weiter bei ihnen bleiben möchte, könnte man sie wohl deswegen kontaktieren. Das bedingt aber einen physikalischen Besuch bei ihnen im Datencenter in Uitikon-Waldegg.

Wir haben eine gesponserte VM von Nine, denke wir können uns die Übung mit einem physischen Ersatz daher sparen.
Diese muss aber noch aufgesetzt werden.

**Comment by dbrgn** [comment]
Zitate werden jedenfalls regelmässig eingetragen, gibt also durchaus noch User nach der Prüfungssession :slightly_smiling_face: Gemäss Analytics so 30-60 am Tag.

> Wir haben eine gesponserte VM von Nine, denke wir können uns die Übung mit einem physischen Ersatz daher sparen.

Stimmt. Ich kann GIB Solutions nach der Migration gerne kontaktieren, mich für das Sponsoring bedanken und sagen, dass sie die Server abschalten können.

**Comment by dbrgn** [comment]
Banner habe ich kurz live reingehackt, sollte auf allen Seiten sichtbar sein!

Die Farbwahl ist nicht schön, dafür auffällig :smile: 

![img](https://tmp.dbrgn.ch/screenshots/20190209140447-kfalvau9.png)

**Comment by thde** [comment]
Sind zwar leider nicht im ersten Semester, aber ich und @lroellin könnten uns ums deployment kümmern für den neuen Server. Arbeite zudem bei der Nine, was den Supportweg etwas verkürzt ;)

**Comment by fabianhauser** [comment]
Das wäre natürlich toll @thde und @lroellin!

Wir hatten unter [studentenportal/deploy-new](https://github.com/studentenportal/deploy-new) vor einer Weile ein neues Ansible-Deployment angefangen, wenn ihr wollt können wir gerne mal zusammen schauen, wie wir da weiterfahren wollen?

**Comment by thde** [comment]
@fabianhauser Danke für die Info. Was ist am Einfachsten? Ich mach mal ein eigenes Repo, welches man dann zum deployment in die studentenportal org forken kann?

Denke der Ansatz mit Docker ist am Einfachsten und lässt sich mit Ansible gut umsetzen.

**Comment by fabianhauser** [comment]
@thde Ich habe euch Zugriff auf das Repository gegeben, dann könnt ihr gerne gleich dort arbeiten 🙂

**Comment by The-Compiler** [comment]
Die Migration ist durch:

![image](https://user-images.githubusercontent.com/625793/76837430-d9cd8600-6832-11ea-9741-c841b67bbf7d.png)

Ich schliesse dieses Issue mal, alles andere kann man dann ja in #6 besprechen.
