### ISSUE TITLE
Mailweiterleitung für team@studentenportal.ch

### ISSUE THREAD

**Issue by The-Compiler** [studentenportal/project#7]
Ists ggf. möglich, mir ne Weiterleitung von team@studentenportal.ch auf studentenportal-team@the-compiler.org einzurichten? Dann kümmere ich mich auch öfters darum, darauf zu reagieren - den Thunderbird zu öffnen vergesse ich öfters mal, und (neo)mutt und mehrere Accounts funktioniert leider eher schlecht...

Alternativ würde ich mir [getmail](http://pyropus.ca/software/getmail/) bei mir als cronjob einrichten, was die Mails via IMAP in meine Mailbox holt.

**Comment by fabianhauser** [comment]
Kannst du sehr gerne machen, wenn du es denn hinkriegst über das Hostpoint UI 😉
Evtl. macht es Sinn, alle E-Mails an die Adresse auch an info@openhsr.ch weiterzuleiten - ich habe das Studentenportal Postfach in letzter Zeit ehrlich gesagt auch nicht mehr angeschaut...

Hmm, ich frage mich, ob wir das selber können oder das jemand vom VSHSR tun muss 🤔

**Comment by fabianhauser** [comment]
Da hier nichts mehr passiert ist, schliesse ich dieses Issue für den Moment. Ich schaue im Rahmen vom open\HSR-Auftrag das Postfach zur Zeit an.

Falls wieder bedarf besteht, gerne wieder öffnen.
